(include-book "io-utilities" :dir :teachpacks)
(set-state-ok t) ; save .lisp file, then press hammer to build
(defun main (state)   ; "main" must be defined with 1 arg (state)
	(let*((state 
		(string-list->file	
			"output.html" 
			'("
				<div id=\"generated_div\">This text was generated by an external ACL2 executable.<hr /> Note that the output file this was originally written to no longer exitst. The python script deleted is as soon as it was done reading from it.<hr /> Just to demonstrate further that we can do this, here is a form.For now, it is just decorative.<form><input type=\"text\"><input type=\"submit\"></form></div>
			") 
			state
		) 
	)))
)